name: Update dependency

on:
  repository_dispatch:
    types: update-dependency

jobs:
  update_version:
    name: Update contracts-interface version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
      - name: npm update
        run: npm install -g npm@8.11.0
      - name: Update @synthetixio/contracts-interface dependency
        run: |
          npm install --legacy-peer-deps --no-audit
          npm install @synthetixio/contracts-interface@${{ github.event.client_payload.version }} --save-exact --legacy-peer-deps
      - name: Commit changes
        run: |
          git config --global user.email "team@synthetix.io" && git config --global user.name "Synthetix Team"
          git commit -am 'contracts-interface@${{ github.event.client_payload.version }}'
          git push origin dev
